// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Definition/SceneDefinition.proto

#ifndef PROTOBUF_Definition_2fSceneDefinition_2eproto__INCLUDED
#define PROTOBUF_Definition_2fSceneDefinition_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "Proto/Common/System.pb.h"
#include "Proto/Common/Object.pb.h"
#include "Proto/Common/Property.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Definition_2fSceneDefinition_2eproto();
void protobuf_AssignDesc_Definition_2fSceneDefinition_2eproto();
void protobuf_ShutdownFile_Definition_2fSceneDefinition_2eproto();

class SceneDefinitionProto;
class SceneDefinitionProto_LinkProto;

// ===================================================================

class SceneDefinitionProto_LinkProto : public ::google::protobuf::Message {
 public:
  SceneDefinitionProto_LinkProto();
  virtual ~SceneDefinitionProto_LinkProto();
  
  SceneDefinitionProto_LinkProto(const SceneDefinitionProto_LinkProto& from);
  
  inline SceneDefinitionProto_LinkProto& operator=(const SceneDefinitionProto_LinkProto& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SceneDefinitionProto_LinkProto& default_instance();
  
  void Swap(SceneDefinitionProto_LinkProto* other);
  
  // implements Message ----------------------------------------------
  
  SceneDefinitionProto_LinkProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SceneDefinitionProto_LinkProto& from);
  void MergeFrom(const SceneDefinitionProto_LinkProto& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string subject = 30;
  inline bool has_subject() const;
  inline void clear_subject();
  static const int kSubjectFieldNumber = 30;
  inline const ::std::string& subject() const;
  inline void set_subject(const ::std::string& value);
  inline void set_subject(const char* value);
  inline void set_subject(const char* value, size_t size);
  inline ::std::string* mutable_subject();
  inline ::std::string* release_subject();
  
  // required string observer = 31;
  inline bool has_observer() const;
  inline void clear_observer();
  static const int kObserverFieldNumber = 31;
  inline const ::std::string& observer() const;
  inline void set_observer(const ::std::string& value);
  inline void set_observer(const char* value);
  inline void set_observer(const char* value, size_t size);
  inline ::std::string* mutable_observer();
  inline ::std::string* release_observer();
  
  // required .SystemProto.Type subjectSystemType = 32;
  inline bool has_subjectsystemtype() const;
  inline void clear_subjectsystemtype();
  static const int kSubjectSystemTypeFieldNumber = 32;
  inline ::SystemProto_Type subjectsystemtype() const;
  inline void set_subjectsystemtype(::SystemProto_Type value);
  
  // required .SystemProto.Type observerSystemType = 33;
  inline bool has_observersystemtype() const;
  inline void clear_observersystemtype();
  static const int kObserverSystemTypeFieldNumber = 33;
  inline ::SystemProto_Type observersystemtype() const;
  inline void set_observersystemtype(::SystemProto_Type value);
  
  // @@protoc_insertion_point(class_scope:SceneDefinitionProto.LinkProto)
 private:
  inline void set_has_subject();
  inline void clear_has_subject();
  inline void set_has_observer();
  inline void clear_has_observer();
  inline void set_has_subjectsystemtype();
  inline void clear_has_subjectsystemtype();
  inline void set_has_observersystemtype();
  inline void clear_has_observersystemtype();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* subject_;
  ::std::string* observer_;
  int subjectsystemtype_;
  int observersystemtype_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_Definition_2fSceneDefinition_2eproto();
  friend void protobuf_AssignDesc_Definition_2fSceneDefinition_2eproto();
  friend void protobuf_ShutdownFile_Definition_2fSceneDefinition_2eproto();
  
  void InitAsDefaultInstance();
  static SceneDefinitionProto_LinkProto* default_instance_;
};
// -------------------------------------------------------------------

class SceneDefinitionProto : public ::google::protobuf::Message {
 public:
  SceneDefinitionProto();
  virtual ~SceneDefinitionProto();
  
  SceneDefinitionProto(const SceneDefinitionProto& from);
  
  inline SceneDefinitionProto& operator=(const SceneDefinitionProto& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SceneDefinitionProto& default_instance();
  
  void Swap(SceneDefinitionProto* other);
  
  // implements Message ----------------------------------------------
  
  SceneDefinitionProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SceneDefinitionProto& from);
  void MergeFrom(const SceneDefinitionProto& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef SceneDefinitionProto_LinkProto LinkProto;
  
  // accessors -------------------------------------------------------
  
  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // repeated .SystemProto systems = 2;
  inline int systems_size() const;
  inline void clear_systems();
  static const int kSystemsFieldNumber = 2;
  inline const ::SystemProto& systems(int index) const;
  inline ::SystemProto* mutable_systems(int index);
  inline ::SystemProto* add_systems();
  inline const ::google::protobuf::RepeatedPtrField< ::SystemProto >&
      systems() const;
  inline ::google::protobuf::RepeatedPtrField< ::SystemProto >*
      mutable_systems();
  
  // repeated .ObjectProto objects = 3;
  inline int objects_size() const;
  inline void clear_objects();
  static const int kObjectsFieldNumber = 3;
  inline const ::ObjectProto& objects(int index) const;
  inline ::ObjectProto* mutable_objects(int index);
  inline ::ObjectProto* add_objects();
  inline const ::google::protobuf::RepeatedPtrField< ::ObjectProto >&
      objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::ObjectProto >*
      mutable_objects();
  
  // repeated .SceneDefinitionProto.LinkProto links = 4;
  inline int links_size() const;
  inline void clear_links();
  static const int kLinksFieldNumber = 4;
  inline const ::SceneDefinitionProto_LinkProto& links(int index) const;
  inline ::SceneDefinitionProto_LinkProto* mutable_links(int index);
  inline ::SceneDefinitionProto_LinkProto* add_links();
  inline const ::google::protobuf::RepeatedPtrField< ::SceneDefinitionProto_LinkProto >&
      links() const;
  inline ::google::protobuf::RepeatedPtrField< ::SceneDefinitionProto_LinkProto >*
      mutable_links();
  
  // @@protoc_insertion_point(class_scope:SceneDefinitionProto)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::SystemProto > systems_;
  ::google::protobuf::RepeatedPtrField< ::ObjectProto > objects_;
  ::google::protobuf::RepeatedPtrField< ::SceneDefinitionProto_LinkProto > links_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_Definition_2fSceneDefinition_2eproto();
  friend void protobuf_AssignDesc_Definition_2fSceneDefinition_2eproto();
  friend void protobuf_ShutdownFile_Definition_2fSceneDefinition_2eproto();
  
  void InitAsDefaultInstance();
  static SceneDefinitionProto* default_instance_;
};
// ===================================================================


// ===================================================================

// SceneDefinitionProto_LinkProto

// required string subject = 30;
inline bool SceneDefinitionProto_LinkProto::has_subject() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SceneDefinitionProto_LinkProto::set_has_subject() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SceneDefinitionProto_LinkProto::clear_has_subject() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SceneDefinitionProto_LinkProto::clear_subject() {
  if (subject_ != &::google::protobuf::internal::kEmptyString) {
    subject_->clear();
  }
  clear_has_subject();
}
inline const ::std::string& SceneDefinitionProto_LinkProto::subject() const {
  return *subject_;
}
inline void SceneDefinitionProto_LinkProto::set_subject(const ::std::string& value) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    subject_ = new ::std::string;
  }
  subject_->assign(value);
}
inline void SceneDefinitionProto_LinkProto::set_subject(const char* value) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    subject_ = new ::std::string;
  }
  subject_->assign(value);
}
inline void SceneDefinitionProto_LinkProto::set_subject(const char* value, size_t size) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    subject_ = new ::std::string;
  }
  subject_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SceneDefinitionProto_LinkProto::mutable_subject() {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    subject_ = new ::std::string;
  }
  return subject_;
}
inline ::std::string* SceneDefinitionProto_LinkProto::release_subject() {
  clear_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = subject_;
    subject_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string observer = 31;
inline bool SceneDefinitionProto_LinkProto::has_observer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SceneDefinitionProto_LinkProto::set_has_observer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SceneDefinitionProto_LinkProto::clear_has_observer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SceneDefinitionProto_LinkProto::clear_observer() {
  if (observer_ != &::google::protobuf::internal::kEmptyString) {
    observer_->clear();
  }
  clear_has_observer();
}
inline const ::std::string& SceneDefinitionProto_LinkProto::observer() const {
  return *observer_;
}
inline void SceneDefinitionProto_LinkProto::set_observer(const ::std::string& value) {
  set_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    observer_ = new ::std::string;
  }
  observer_->assign(value);
}
inline void SceneDefinitionProto_LinkProto::set_observer(const char* value) {
  set_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    observer_ = new ::std::string;
  }
  observer_->assign(value);
}
inline void SceneDefinitionProto_LinkProto::set_observer(const char* value, size_t size) {
  set_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    observer_ = new ::std::string;
  }
  observer_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SceneDefinitionProto_LinkProto::mutable_observer() {
  set_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    observer_ = new ::std::string;
  }
  return observer_;
}
inline ::std::string* SceneDefinitionProto_LinkProto::release_observer() {
  clear_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = observer_;
    observer_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required .SystemProto.Type subjectSystemType = 32;
inline bool SceneDefinitionProto_LinkProto::has_subjectsystemtype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SceneDefinitionProto_LinkProto::set_has_subjectsystemtype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SceneDefinitionProto_LinkProto::clear_has_subjectsystemtype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SceneDefinitionProto_LinkProto::clear_subjectsystemtype() {
  subjectsystemtype_ = 0;
  clear_has_subjectsystemtype();
}
inline ::SystemProto_Type SceneDefinitionProto_LinkProto::subjectsystemtype() const {
  return static_cast< ::SystemProto_Type >(subjectsystemtype_);
}
inline void SceneDefinitionProto_LinkProto::set_subjectsystemtype(::SystemProto_Type value) {
  GOOGLE_DCHECK(::SystemProto_Type_IsValid(value));
  set_has_subjectsystemtype();
  subjectsystemtype_ = value;
}

// required .SystemProto.Type observerSystemType = 33;
inline bool SceneDefinitionProto_LinkProto::has_observersystemtype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SceneDefinitionProto_LinkProto::set_has_observersystemtype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SceneDefinitionProto_LinkProto::clear_has_observersystemtype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SceneDefinitionProto_LinkProto::clear_observersystemtype() {
  observersystemtype_ = 0;
  clear_has_observersystemtype();
}
inline ::SystemProto_Type SceneDefinitionProto_LinkProto::observersystemtype() const {
  return static_cast< ::SystemProto_Type >(observersystemtype_);
}
inline void SceneDefinitionProto_LinkProto::set_observersystemtype(::SystemProto_Type value) {
  GOOGLE_DCHECK(::SystemProto_Type_IsValid(value));
  set_has_observersystemtype();
  observersystemtype_ = value;
}

// -------------------------------------------------------------------

// SceneDefinitionProto

// required string name = 1;
inline bool SceneDefinitionProto::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SceneDefinitionProto::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SceneDefinitionProto::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SceneDefinitionProto::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& SceneDefinitionProto::name() const {
  return *name_;
}
inline void SceneDefinitionProto::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void SceneDefinitionProto::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void SceneDefinitionProto::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SceneDefinitionProto::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* SceneDefinitionProto::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .SystemProto systems = 2;
inline int SceneDefinitionProto::systems_size() const {
  return systems_.size();
}
inline void SceneDefinitionProto::clear_systems() {
  systems_.Clear();
}
inline const ::SystemProto& SceneDefinitionProto::systems(int index) const {
  return systems_.Get(index);
}
inline ::SystemProto* SceneDefinitionProto::mutable_systems(int index) {
  return systems_.Mutable(index);
}
inline ::SystemProto* SceneDefinitionProto::add_systems() {
  return systems_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SystemProto >&
SceneDefinitionProto::systems() const {
  return systems_;
}
inline ::google::protobuf::RepeatedPtrField< ::SystemProto >*
SceneDefinitionProto::mutable_systems() {
  return &systems_;
}

// repeated .ObjectProto objects = 3;
inline int SceneDefinitionProto::objects_size() const {
  return objects_.size();
}
inline void SceneDefinitionProto::clear_objects() {
  objects_.Clear();
}
inline const ::ObjectProto& SceneDefinitionProto::objects(int index) const {
  return objects_.Get(index);
}
inline ::ObjectProto* SceneDefinitionProto::mutable_objects(int index) {
  return objects_.Mutable(index);
}
inline ::ObjectProto* SceneDefinitionProto::add_objects() {
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ObjectProto >&
SceneDefinitionProto::objects() const {
  return objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::ObjectProto >*
SceneDefinitionProto::mutable_objects() {
  return &objects_;
}

// repeated .SceneDefinitionProto.LinkProto links = 4;
inline int SceneDefinitionProto::links_size() const {
  return links_.size();
}
inline void SceneDefinitionProto::clear_links() {
  links_.Clear();
}
inline const ::SceneDefinitionProto_LinkProto& SceneDefinitionProto::links(int index) const {
  return links_.Get(index);
}
inline ::SceneDefinitionProto_LinkProto* SceneDefinitionProto::mutable_links(int index) {
  return links_.Mutable(index);
}
inline ::SceneDefinitionProto_LinkProto* SceneDefinitionProto::add_links() {
  return links_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SceneDefinitionProto_LinkProto >&
SceneDefinitionProto::links() const {
  return links_;
}
inline ::google::protobuf::RepeatedPtrField< ::SceneDefinitionProto_LinkProto >*
SceneDefinitionProto::mutable_links() {
  return &links_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Definition_2fSceneDefinition_2eproto__INCLUDED
