// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/Definition/GlobalDefinition.proto

package fr.kissy.hellion.proto.definition;

public final class GlobalDefinitionDto {
  private GlobalDefinitionDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GlobalDefinitionProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string startupScene = 1;
    boolean hasStartupScene();
    String getStartupScene();
    
    // repeated .PropertyProto properties = 2;
    java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> 
        getPropertiesList();
    fr.kissy.hellion.proto.common.PropertyDto.PropertyProto getProperties(int index);
    int getPropertiesCount();
    java.util.List<? extends fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> 
        getPropertiesOrBuilderList();
    fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder getPropertiesOrBuilder(
        int index);
    
    // repeated .SystemProto systems = 3;
    java.util.List<fr.kissy.hellion.proto.common.SystemDto.SystemProto> 
        getSystemsList();
    fr.kissy.hellion.proto.common.SystemDto.SystemProto getSystems(int index);
    int getSystemsCount();
    java.util.List<? extends fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder> 
        getSystemsOrBuilderList();
    fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder getSystemsOrBuilder(
        int index);
    
    // repeated string scenes = 4;
    java.util.List<String> getScenesList();
    int getScenesCount();
    String getScenes(int index);
  }
  public static final class GlobalDefinitionProto extends
      com.google.protobuf.GeneratedMessage
      implements GlobalDefinitionProtoOrBuilder {
    // Use GlobalDefinitionProto.newBuilder() to construct.
    private GlobalDefinitionProto(Builder builder) {
      super(builder);
    }
    private GlobalDefinitionProto(boolean noInit) {}
    
    private static final GlobalDefinitionProto defaultInstance;
    public static GlobalDefinitionProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public GlobalDefinitionProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.kissy.hellion.proto.definition.GlobalDefinitionDto.internal_static_GlobalDefinitionProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.kissy.hellion.proto.definition.GlobalDefinitionDto.internal_static_GlobalDefinitionProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string startupScene = 1;
    public static final int STARTUPSCENE_FIELD_NUMBER = 1;
    private java.lang.Object startupScene_;
    public boolean hasStartupScene() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getStartupScene() {
      java.lang.Object ref = startupScene_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          startupScene_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStartupSceneBytes() {
      java.lang.Object ref = startupScene_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        startupScene_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .PropertyProto properties = 2;
    public static final int PROPERTIES_FIELD_NUMBER = 2;
    private java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> properties_;
    public java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> getPropertiesList() {
      return properties_;
    }
    public java.util.List<? extends fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> 
        getPropertiesOrBuilderList() {
      return properties_;
    }
    public int getPropertiesCount() {
      return properties_.size();
    }
    public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto getProperties(int index) {
      return properties_.get(index);
    }
    public fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder getPropertiesOrBuilder(
        int index) {
      return properties_.get(index);
    }
    
    // repeated .SystemProto systems = 3;
    public static final int SYSTEMS_FIELD_NUMBER = 3;
    private java.util.List<fr.kissy.hellion.proto.common.SystemDto.SystemProto> systems_;
    public java.util.List<fr.kissy.hellion.proto.common.SystemDto.SystemProto> getSystemsList() {
      return systems_;
    }
    public java.util.List<? extends fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder> 
        getSystemsOrBuilderList() {
      return systems_;
    }
    public int getSystemsCount() {
      return systems_.size();
    }
    public fr.kissy.hellion.proto.common.SystemDto.SystemProto getSystems(int index) {
      return systems_.get(index);
    }
    public fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder getSystemsOrBuilder(
        int index) {
      return systems_.get(index);
    }
    
    // repeated string scenes = 4;
    public static final int SCENES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList scenes_;
    public java.util.List<String>
        getScenesList() {
      return scenes_;
    }
    public int getScenesCount() {
      return scenes_.size();
    }
    public String getScenes(int index) {
      return scenes_.get(index);
    }
    
    private void initFields() {
      startupScene_ = "";
      properties_ = java.util.Collections.emptyList();
      systems_ = java.util.Collections.emptyList();
      scenes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStartupScene()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropertiesCount(); i++) {
        if (!getProperties(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getSystemsCount(); i++) {
        if (!getSystems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStartupSceneBytes());
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeMessage(2, properties_.get(i));
      }
      for (int i = 0; i < systems_.size(); i++) {
        output.writeMessage(3, systems_.get(i));
      }
      for (int i = 0; i < scenes_.size(); i++) {
        output.writeBytes(4, scenes_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStartupSceneBytes());
      }
      for (int i = 0; i < properties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, properties_.get(i));
      }
      for (int i = 0; i < systems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, systems_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < scenes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(scenes_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getScenesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.kissy.hellion.proto.definition.GlobalDefinitionDto.internal_static_GlobalDefinitionProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.kissy.hellion.proto.definition.GlobalDefinitionDto.internal_static_GlobalDefinitionProto_fieldAccessorTable;
      }
      
      // Construct using fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertiesFieldBuilder();
          getSystemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        startupScene_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          propertiesBuilder_.clear();
        }
        if (systemsBuilder_ == null) {
          systems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          systemsBuilder_.clear();
        }
        scenes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto.getDescriptor();
      }
      
      public fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto getDefaultInstanceForType() {
        return fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto.getDefaultInstance();
      }
      
      public fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto build() {
        fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto buildPartial() {
        fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto result = new fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startupScene_ = startupScene_;
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        if (systemsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            systems_ = java.util.Collections.unmodifiableList(systems_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.systems_ = systems_;
        } else {
          result.systems_ = systemsBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          scenes_ = new com.google.protobuf.UnmodifiableLazyStringList(
              scenes_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.scenes_ = scenes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto) {
          return mergeFrom((fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto other) {
        if (other == fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto.getDefaultInstance()) return this;
        if (other.hasStartupScene()) {
          setStartupScene(other.getStartupScene());
        }
        if (propertiesBuilder_ == null) {
          if (!other.properties_.isEmpty()) {
            if (properties_.isEmpty()) {
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePropertiesIsMutable();
              properties_.addAll(other.properties_);
            }
            onChanged();
          }
        } else {
          if (!other.properties_.isEmpty()) {
            if (propertiesBuilder_.isEmpty()) {
              propertiesBuilder_.dispose();
              propertiesBuilder_ = null;
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000002);
              propertiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertiesFieldBuilder() : null;
            } else {
              propertiesBuilder_.addAllMessages(other.properties_);
            }
          }
        }
        if (systemsBuilder_ == null) {
          if (!other.systems_.isEmpty()) {
            if (systems_.isEmpty()) {
              systems_ = other.systems_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSystemsIsMutable();
              systems_.addAll(other.systems_);
            }
            onChanged();
          }
        } else {
          if (!other.systems_.isEmpty()) {
            if (systemsBuilder_.isEmpty()) {
              systemsBuilder_.dispose();
              systemsBuilder_ = null;
              systems_ = other.systems_;
              bitField0_ = (bitField0_ & ~0x00000004);
              systemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSystemsFieldBuilder() : null;
            } else {
              systemsBuilder_.addAllMessages(other.systems_);
            }
          }
        }
        if (!other.scenes_.isEmpty()) {
          if (scenes_.isEmpty()) {
            scenes_ = other.scenes_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureScenesIsMutable();
            scenes_.addAll(other.scenes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStartupScene()) {
          
          return false;
        }
        for (int i = 0; i < getPropertiesCount(); i++) {
          if (!getProperties(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getSystemsCount(); i++) {
          if (!getSystems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              startupScene_ = input.readBytes();
              break;
            }
            case 18: {
              fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder subBuilder = fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperties(subBuilder.buildPartial());
              break;
            }
            case 26: {
              fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder subBuilder = fr.kissy.hellion.proto.common.SystemDto.SystemProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSystems(subBuilder.buildPartial());
              break;
            }
            case 34: {
              ensureScenesIsMutable();
              scenes_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string startupScene = 1;
      private java.lang.Object startupScene_ = "";
      public boolean hasStartupScene() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getStartupScene() {
        java.lang.Object ref = startupScene_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          startupScene_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStartupScene(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        startupScene_ = value;
        onChanged();
        return this;
      }
      public Builder clearStartupScene() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startupScene_ = getDefaultInstance().getStartupScene();
        onChanged();
        return this;
      }
      void setStartupScene(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        startupScene_ = value;
        onChanged();
      }
      
      // repeated .PropertyProto properties = 2;
      private java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> properties_ =
        java.util.Collections.emptyList();
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          properties_ = new java.util.ArrayList<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto>(properties_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.hellion.proto.common.PropertyDto.PropertyProto, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder, fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> propertiesBuilder_;
      
      public java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> getPropertiesList() {
        if (propertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(properties_);
        } else {
          return propertiesBuilder_.getMessageList();
        }
      }
      public int getPropertiesCount() {
        if (propertiesBuilder_ == null) {
          return properties_.size();
        } else {
          return propertiesBuilder_.getCount();
        }
      }
      public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto getProperties(int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);
        } else {
          return propertiesBuilder_.getMessage(index);
        }
      }
      public Builder setProperties(
          int index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.set(index, value);
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProperties(
          int index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProperties(fr.kissy.hellion.proto.common.PropertyDto.PropertyProto value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProperties(
          int index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(index, value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProperties(
          fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProperties(
          int index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProperties(
          java.lang.Iterable<? extends fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> values) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          super.addAll(values, properties_);
          onChanged();
        } else {
          propertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      public Builder removeProperties(int index) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.remove(index);
          onChanged();
        } else {
          propertiesBuilder_.remove(index);
        }
        return this;
      }
      public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder getPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().getBuilder(index);
      }
      public fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder getPropertiesOrBuilder(
          int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);  } else {
          return propertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> 
           getPropertiesOrBuilderList() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(properties_);
        }
      }
      public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder addPropertiesBuilder() {
        return getPropertiesFieldBuilder().addBuilder(
            fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.getDefaultInstance());
      }
      public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder addPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().addBuilder(
            index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.getDefaultInstance());
      }
      public java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder> 
           getPropertiesBuilderList() {
        return getPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.hellion.proto.common.PropertyDto.PropertyProto, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder, fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.kissy.hellion.proto.common.PropertyDto.PropertyProto, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder, fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder>(
                  properties_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }
      
      // repeated .SystemProto systems = 3;
      private java.util.List<fr.kissy.hellion.proto.common.SystemDto.SystemProto> systems_ =
        java.util.Collections.emptyList();
      private void ensureSystemsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          systems_ = new java.util.ArrayList<fr.kissy.hellion.proto.common.SystemDto.SystemProto>(systems_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.hellion.proto.common.SystemDto.SystemProto, fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder, fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder> systemsBuilder_;
      
      public java.util.List<fr.kissy.hellion.proto.common.SystemDto.SystemProto> getSystemsList() {
        if (systemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(systems_);
        } else {
          return systemsBuilder_.getMessageList();
        }
      }
      public int getSystemsCount() {
        if (systemsBuilder_ == null) {
          return systems_.size();
        } else {
          return systemsBuilder_.getCount();
        }
      }
      public fr.kissy.hellion.proto.common.SystemDto.SystemProto getSystems(int index) {
        if (systemsBuilder_ == null) {
          return systems_.get(index);
        } else {
          return systemsBuilder_.getMessage(index);
        }
      }
      public Builder setSystems(
          int index, fr.kissy.hellion.proto.common.SystemDto.SystemProto value) {
        if (systemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemsIsMutable();
          systems_.set(index, value);
          onChanged();
        } else {
          systemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSystems(
          int index, fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder builderForValue) {
        if (systemsBuilder_ == null) {
          ensureSystemsIsMutable();
          systems_.set(index, builderForValue.build());
          onChanged();
        } else {
          systemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSystems(fr.kissy.hellion.proto.common.SystemDto.SystemProto value) {
        if (systemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemsIsMutable();
          systems_.add(value);
          onChanged();
        } else {
          systemsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSystems(
          int index, fr.kissy.hellion.proto.common.SystemDto.SystemProto value) {
        if (systemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemsIsMutable();
          systems_.add(index, value);
          onChanged();
        } else {
          systemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSystems(
          fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder builderForValue) {
        if (systemsBuilder_ == null) {
          ensureSystemsIsMutable();
          systems_.add(builderForValue.build());
          onChanged();
        } else {
          systemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSystems(
          int index, fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder builderForValue) {
        if (systemsBuilder_ == null) {
          ensureSystemsIsMutable();
          systems_.add(index, builderForValue.build());
          onChanged();
        } else {
          systemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSystems(
          java.lang.Iterable<? extends fr.kissy.hellion.proto.common.SystemDto.SystemProto> values) {
        if (systemsBuilder_ == null) {
          ensureSystemsIsMutable();
          super.addAll(values, systems_);
          onChanged();
        } else {
          systemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSystems() {
        if (systemsBuilder_ == null) {
          systems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          systemsBuilder_.clear();
        }
        return this;
      }
      public Builder removeSystems(int index) {
        if (systemsBuilder_ == null) {
          ensureSystemsIsMutable();
          systems_.remove(index);
          onChanged();
        } else {
          systemsBuilder_.remove(index);
        }
        return this;
      }
      public fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder getSystemsBuilder(
          int index) {
        return getSystemsFieldBuilder().getBuilder(index);
      }
      public fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder getSystemsOrBuilder(
          int index) {
        if (systemsBuilder_ == null) {
          return systems_.get(index);  } else {
          return systemsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder> 
           getSystemsOrBuilderList() {
        if (systemsBuilder_ != null) {
          return systemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(systems_);
        }
      }
      public fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder addSystemsBuilder() {
        return getSystemsFieldBuilder().addBuilder(
            fr.kissy.hellion.proto.common.SystemDto.SystemProto.getDefaultInstance());
      }
      public fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder addSystemsBuilder(
          int index) {
        return getSystemsFieldBuilder().addBuilder(
            index, fr.kissy.hellion.proto.common.SystemDto.SystemProto.getDefaultInstance());
      }
      public java.util.List<fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder> 
           getSystemsBuilderList() {
        return getSystemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.hellion.proto.common.SystemDto.SystemProto, fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder, fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder> 
          getSystemsFieldBuilder() {
        if (systemsBuilder_ == null) {
          systemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.kissy.hellion.proto.common.SystemDto.SystemProto, fr.kissy.hellion.proto.common.SystemDto.SystemProto.Builder, fr.kissy.hellion.proto.common.SystemDto.SystemProtoOrBuilder>(
                  systems_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          systems_ = null;
        }
        return systemsBuilder_;
      }
      
      // repeated string scenes = 4;
      private com.google.protobuf.LazyStringList scenes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureScenesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          scenes_ = new com.google.protobuf.LazyStringArrayList(scenes_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getScenesList() {
        return java.util.Collections.unmodifiableList(scenes_);
      }
      public int getScenesCount() {
        return scenes_.size();
      }
      public String getScenes(int index) {
        return scenes_.get(index);
      }
      public Builder setScenes(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureScenesIsMutable();
        scenes_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addScenes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureScenesIsMutable();
        scenes_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllScenes(
          java.lang.Iterable<String> values) {
        ensureScenesIsMutable();
        super.addAll(values, scenes_);
        onChanged();
        return this;
      }
      public Builder clearScenes() {
        scenes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addScenes(com.google.protobuf.ByteString value) {
        ensureScenesIsMutable();
        scenes_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:GlobalDefinitionProto)
    }
    
    static {
      defaultInstance = new GlobalDefinitionProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:GlobalDefinitionProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalDefinitionProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GlobalDefinitionProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'Proto/Definition/GlobalDefinition.prot" +
      "o\032\031Proto/Common/System.proto\032\033Proto/Comm" +
      "on/Property.proto\"\200\001\n\025GlobalDefinitionPr" +
      "oto\022\024\n\014startupScene\030\001 \002(\t\022\"\n\nproperties\030" +
      "\002 \003(\0132\016.PropertyProto\022\035\n\007systems\030\003 \003(\0132\014" +
      ".SystemProto\022\016\n\006scenes\030\004 \003(\tB;\n!fr.kissy" +
      ".hellion.proto.definitionB\023GlobalDefinit" +
      "ionDto\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GlobalDefinitionProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GlobalDefinitionProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GlobalDefinitionProto_descriptor,
              new java.lang.String[] { "StartupScene", "Properties", "Systems", "Scenes", },
              fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto.class,
              fr.kissy.hellion.proto.definition.GlobalDefinitionDto.GlobalDefinitionProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fr.kissy.hellion.proto.common.SystemDto.getDescriptor(),
          fr.kissy.hellion.proto.common.PropertyDto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
