// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Object.proto

#ifndef PROTOBUF_Object_2eproto__INCLUDED
#define PROTOBUF_Object_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "System.pb.h"
#include "Property.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Object_2eproto();
void protobuf_AssignDesc_Object_2eproto();
void protobuf_ShutdownFile_Object_2eproto();

class Object;
class Object_SystemProperties;

// ===================================================================

class Object_SystemProperties : public ::google::protobuf::Message {
 public:
  Object_SystemProperties();
  virtual ~Object_SystemProperties();
  
  Object_SystemProperties(const Object_SystemProperties& from);
  
  inline Object_SystemProperties& operator=(const Object_SystemProperties& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Object_SystemProperties& default_instance();
  
  void Swap(Object_SystemProperties* other);
  
  // implements Message ----------------------------------------------
  
  Object_SystemProperties* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Object_SystemProperties& from);
  void MergeFrom(const Object_SystemProperties& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .System.Type systemType = 10;
  inline bool has_systemtype() const;
  inline void clear_systemtype();
  static const int kSystemTypeFieldNumber = 10;
  inline ::System_Type systemtype() const;
  inline void set_systemtype(::System_Type value);
  
  // repeated .Property properties = 11;
  inline int properties_size() const;
  inline void clear_properties();
  static const int kPropertiesFieldNumber = 11;
  inline const ::Property& properties(int index) const;
  inline ::Property* mutable_properties(int index);
  inline ::Property* add_properties();
  inline const ::google::protobuf::RepeatedPtrField< ::Property >&
      properties() const;
  inline ::google::protobuf::RepeatedPtrField< ::Property >*
      mutable_properties();
  
  // optional string type = 12;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 12;
  inline const ::std::string& type() const;
  inline void set_type(const ::std::string& value);
  inline void set_type(const char* value);
  inline void set_type(const char* value, size_t size);
  inline ::std::string* mutable_type();
  inline ::std::string* release_type();
  
  // @@protoc_insertion_point(class_scope:Object.SystemProperties)
 private:
  inline void set_has_systemtype();
  inline void clear_has_systemtype();
  inline void set_has_type();
  inline void clear_has_type();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::Property > properties_;
  ::std::string* type_;
  int systemtype_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_Object_2eproto();
  friend void protobuf_AssignDesc_Object_2eproto();
  friend void protobuf_ShutdownFile_Object_2eproto();
  
  void InitAsDefaultInstance();
  static Object_SystemProperties* default_instance_;
};
// -------------------------------------------------------------------

class Object : public ::google::protobuf::Message {
 public:
  Object();
  virtual ~Object();
  
  Object(const Object& from);
  
  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Object& default_instance();
  
  void Swap(Object* other);
  
  // implements Message ----------------------------------------------
  
  Object* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Object& from);
  void MergeFrom(const Object& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Object_SystemProperties SystemProperties;
  
  // accessors -------------------------------------------------------
  
  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // repeated .Object.SystemProperties systemProperties = 2;
  inline int systemproperties_size() const;
  inline void clear_systemproperties();
  static const int kSystemPropertiesFieldNumber = 2;
  inline const ::Object_SystemProperties& systemproperties(int index) const;
  inline ::Object_SystemProperties* mutable_systemproperties(int index);
  inline ::Object_SystemProperties* add_systemproperties();
  inline const ::google::protobuf::RepeatedPtrField< ::Object_SystemProperties >&
      systemproperties() const;
  inline ::google::protobuf::RepeatedPtrField< ::Object_SystemProperties >*
      mutable_systemproperties();
  
  // @@protoc_insertion_point(class_scope:Object)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::Object_SystemProperties > systemproperties_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_Object_2eproto();
  friend void protobuf_AssignDesc_Object_2eproto();
  friend void protobuf_ShutdownFile_Object_2eproto();
  
  void InitAsDefaultInstance();
  static Object* default_instance_;
};
// ===================================================================


// ===================================================================

// Object_SystemProperties

// required .System.Type systemType = 10;
inline bool Object_SystemProperties::has_systemtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Object_SystemProperties::set_has_systemtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Object_SystemProperties::clear_has_systemtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Object_SystemProperties::clear_systemtype() {
  systemtype_ = 0;
  clear_has_systemtype();
}
inline ::System_Type Object_SystemProperties::systemtype() const {
  return static_cast< ::System_Type >(systemtype_);
}
inline void Object_SystemProperties::set_systemtype(::System_Type value) {
  GOOGLE_DCHECK(::System_Type_IsValid(value));
  set_has_systemtype();
  systemtype_ = value;
}

// repeated .Property properties = 11;
inline int Object_SystemProperties::properties_size() const {
  return properties_.size();
}
inline void Object_SystemProperties::clear_properties() {
  properties_.Clear();
}
inline const ::Property& Object_SystemProperties::properties(int index) const {
  return properties_.Get(index);
}
inline ::Property* Object_SystemProperties::mutable_properties(int index) {
  return properties_.Mutable(index);
}
inline ::Property* Object_SystemProperties::add_properties() {
  return properties_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Property >&
Object_SystemProperties::properties() const {
  return properties_;
}
inline ::google::protobuf::RepeatedPtrField< ::Property >*
Object_SystemProperties::mutable_properties() {
  return &properties_;
}

// optional string type = 12;
inline bool Object_SystemProperties::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Object_SystemProperties::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Object_SystemProperties::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Object_SystemProperties::clear_type() {
  if (type_ != &::google::protobuf::internal::kEmptyString) {
    type_->clear();
  }
  clear_has_type();
}
inline const ::std::string& Object_SystemProperties::type() const {
  return *type_;
}
inline void Object_SystemProperties::set_type(const ::std::string& value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    type_ = new ::std::string;
  }
  type_->assign(value);
}
inline void Object_SystemProperties::set_type(const char* value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    type_ = new ::std::string;
  }
  type_->assign(value);
}
inline void Object_SystemProperties::set_type(const char* value, size_t size) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    type_ = new ::std::string;
  }
  type_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Object_SystemProperties::mutable_type() {
  set_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    type_ = new ::std::string;
  }
  return type_;
}
inline ::std::string* Object_SystemProperties::release_type() {
  clear_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = type_;
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// Object

// required string name = 1;
inline bool Object::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Object::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Object::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Object::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Object::name() const {
  return *name_;
}
inline void Object::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Object::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Object::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Object::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Object::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .Object.SystemProperties systemProperties = 2;
inline int Object::systemproperties_size() const {
  return systemproperties_.size();
}
inline void Object::clear_systemproperties() {
  systemproperties_.Clear();
}
inline const ::Object_SystemProperties& Object::systemproperties(int index) const {
  return systemproperties_.Get(index);
}
inline ::Object_SystemProperties* Object::mutable_systemproperties(int index) {
  return systemproperties_.Mutable(index);
}
inline ::Object_SystemProperties* Object::add_systemproperties() {
  return systemproperties_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Object_SystemProperties >&
Object::systemproperties() const {
  return systemproperties_;
}
inline ::google::protobuf::RepeatedPtrField< ::Object_SystemProperties >*
Object::mutable_systemproperties() {
  return &systemproperties_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Object_2eproto__INCLUDED
