// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sdf.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Proto {

namespace {

const ::google::protobuf::Descriptor* Sdf_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Sdf_reflection_ = NULL;
const ::google::protobuf::Descriptor* Sdf_SystemProperties_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Sdf_SystemProperties_reflection_ = NULL;
const ::google::protobuf::Descriptor* Sdf_ObjectProperties_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Sdf_ObjectProperties_reflection_ = NULL;
const ::google::protobuf::Descriptor* Sdf_Object_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Sdf_Object_reflection_ = NULL;
const ::google::protobuf::Descriptor* Sdf_Link_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Sdf_Link_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_sdf_2eproto() {
  protobuf_AddDesc_sdf_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sdf.proto");
  GOOGLE_CHECK(file != NULL);
  Sdf_descriptor_ = file->message_type(0);
  static const int Sdf_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf, systemproperties_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf, objects_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf, links_),
  };
  Sdf_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Sdf_descriptor_,
      Sdf::default_instance_,
      Sdf_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Sdf));
  Sdf_SystemProperties_descriptor_ = Sdf_descriptor_->nested_type(0);
  static const int Sdf_SystemProperties_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_SystemProperties, systemtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_SystemProperties, properties_),
  };
  Sdf_SystemProperties_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Sdf_SystemProperties_descriptor_,
      Sdf_SystemProperties::default_instance_,
      Sdf_SystemProperties_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_SystemProperties, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_SystemProperties, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Sdf_SystemProperties));
  Sdf_ObjectProperties_descriptor_ = Sdf_descriptor_->nested_type(1);
  static const int Sdf_ObjectProperties_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_ObjectProperties, systemtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_ObjectProperties, objecttype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_ObjectProperties, properties_),
  };
  Sdf_ObjectProperties_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Sdf_ObjectProperties_descriptor_,
      Sdf_ObjectProperties::default_instance_,
      Sdf_ObjectProperties_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_ObjectProperties, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_ObjectProperties, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Sdf_ObjectProperties));
  Sdf_Object_descriptor_ = Sdf_descriptor_->nested_type(2);
  static const int Sdf_Object_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Object, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Object, objectproperties_),
  };
  Sdf_Object_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Sdf_Object_descriptor_,
      Sdf_Object::default_instance_,
      Sdf_Object_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Object, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Object, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Sdf_Object));
  Sdf_Link_descriptor_ = Sdf_descriptor_->nested_type(3);
  static const int Sdf_Link_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Link, subject_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Link, observer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Link, subjectsystem_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Link, observersystem_),
  };
  Sdf_Link_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Sdf_Link_descriptor_,
      Sdf_Link::default_instance_,
      Sdf_Link_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Link, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sdf_Link, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Sdf_Link));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sdf_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Sdf_descriptor_, &Sdf::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Sdf_SystemProperties_descriptor_, &Sdf_SystemProperties::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Sdf_ObjectProperties_descriptor_, &Sdf_ObjectProperties::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Sdf_Object_descriptor_, &Sdf_Object::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Sdf_Link_descriptor_, &Sdf_Link::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sdf_2eproto() {
  delete Sdf::default_instance_;
  delete Sdf_reflection_;
  delete Sdf_SystemProperties::default_instance_;
  delete Sdf_SystemProperties_reflection_;
  delete Sdf_ObjectProperties::default_instance_;
  delete Sdf_ObjectProperties_reflection_;
  delete Sdf_Object::default_instance_;
  delete Sdf_Object_reflection_;
  delete Sdf_Link::default_instance_;
  delete Sdf_Link_reflection_;
}

void protobuf_AddDesc_sdf_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Proto::protobuf_AddDesc_property_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tsdf.proto\022\005Proto\032\016property.proto\"\345\003\n\003S"
    "df\022\014\n\004name\030\001 \002(\t\0225\n\020systemProperties\030\002 \003"
    "(\0132\033.Proto.Sdf.SystemProperties\022\"\n\007objec"
    "ts\030\003 \003(\0132\021.Proto.Sdf.Object\022\036\n\005links\030\004 \003"
    "(\0132\017.Proto.Sdf.Link\032K\n\020SystemProperties\022"
    "\022\n\nsystemType\030\n \002(\t\022#\n\nproperties\030\013 \003(\0132"
    "\017.Proto.Property\032_\n\020ObjectProperties\022\022\n\n"
    "systemType\030\024 \002(\t\022\022\n\nobjectType\030\025 \001(\t\022#\n\n"
    "properties\030\026 \003(\0132\017.Proto.Property\032M\n\006Obj"
    "ect\022\014\n\004name\030\036 \002(\t\0225\n\020objectProperties\030\037 "
    "\003(\0132\033.Proto.Sdf.ObjectProperties\032X\n\004Link"
    "\022\017\n\007subject\030( \002(\t\022\020\n\010observer\030) \002(\t\022\025\n\rs"
    "ubjectSystem\030* \002(\t\022\026\n\016observerSystem\030+ \002"
    "(\tB%\n\026fr.kissy.encoder.protoB\010SdfProto\210\001"
    "\000", 561);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sdf.proto", &protobuf_RegisterTypes);
  Sdf::default_instance_ = new Sdf();
  Sdf_SystemProperties::default_instance_ = new Sdf_SystemProperties();
  Sdf_ObjectProperties::default_instance_ = new Sdf_ObjectProperties();
  Sdf_Object::default_instance_ = new Sdf_Object();
  Sdf_Link::default_instance_ = new Sdf_Link();
  Sdf::default_instance_->InitAsDefaultInstance();
  Sdf_SystemProperties::default_instance_->InitAsDefaultInstance();
  Sdf_ObjectProperties::default_instance_->InitAsDefaultInstance();
  Sdf_Object::default_instance_->InitAsDefaultInstance();
  Sdf_Link::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sdf_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sdf_2eproto {
  StaticDescriptorInitializer_sdf_2eproto() {
    protobuf_AddDesc_sdf_2eproto();
  }
} static_descriptor_initializer_sdf_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int Sdf_SystemProperties::kSystemTypeFieldNumber;
const int Sdf_SystemProperties::kPropertiesFieldNumber;
#endif  // !_MSC_VER

Sdf_SystemProperties::Sdf_SystemProperties()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Sdf_SystemProperties::InitAsDefaultInstance() {
}

Sdf_SystemProperties::Sdf_SystemProperties(const Sdf_SystemProperties& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Sdf_SystemProperties::SharedCtor() {
  _cached_size_ = 0;
  systemtype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Sdf_SystemProperties::~Sdf_SystemProperties() {
  SharedDtor();
}

void Sdf_SystemProperties::SharedDtor() {
  if (systemtype_ != &::google::protobuf::internal::kEmptyString) {
    delete systemtype_;
  }
  if (this != default_instance_) {
  }
}

void Sdf_SystemProperties::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Sdf_SystemProperties::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Sdf_SystemProperties_descriptor_;
}

const Sdf_SystemProperties& Sdf_SystemProperties::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdf_2eproto();  return *default_instance_;
}

Sdf_SystemProperties* Sdf_SystemProperties::default_instance_ = NULL;

Sdf_SystemProperties* Sdf_SystemProperties::New() const {
  return new Sdf_SystemProperties;
}

void Sdf_SystemProperties::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_systemtype()) {
      if (systemtype_ != &::google::protobuf::internal::kEmptyString) {
        systemtype_->clear();
      }
    }
  }
  properties_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Sdf_SystemProperties::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string systemType = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_systemtype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->systemtype().data(), this->systemtype().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_properties;
        break;
      }
      
      // repeated .Proto.Property properties = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_properties:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_properties()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_properties;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Sdf_SystemProperties::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string systemType = 10;
  if (has_systemtype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->systemtype().data(), this->systemtype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      10, this->systemtype(), output);
  }
  
  // repeated .Proto.Property properties = 11;
  for (int i = 0; i < this->properties_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->properties(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Sdf_SystemProperties::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string systemType = 10;
  if (has_systemtype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->systemtype().data(), this->systemtype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->systemtype(), target);
  }
  
  // repeated .Proto.Property properties = 11;
  for (int i = 0; i < this->properties_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, this->properties(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Sdf_SystemProperties::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string systemType = 10;
    if (has_systemtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->systemtype());
    }
    
  }
  // repeated .Proto.Property properties = 11;
  total_size += 1 * this->properties_size();
  for (int i = 0; i < this->properties_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->properties(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Sdf_SystemProperties::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Sdf_SystemProperties* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Sdf_SystemProperties*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Sdf_SystemProperties::MergeFrom(const Sdf_SystemProperties& from) {
  GOOGLE_CHECK_NE(&from, this);
  properties_.MergeFrom(from.properties_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_systemtype()) {
      set_systemtype(from.systemtype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Sdf_SystemProperties::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sdf_SystemProperties::CopyFrom(const Sdf_SystemProperties& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sdf_SystemProperties::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  for (int i = 0; i < properties_size(); i++) {
    if (!this->properties(i).IsInitialized()) return false;
  }
  return true;
}

void Sdf_SystemProperties::Swap(Sdf_SystemProperties* other) {
  if (other != this) {
    std::swap(systemtype_, other->systemtype_);
    properties_.Swap(&other->properties_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Sdf_SystemProperties::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Sdf_SystemProperties_descriptor_;
  metadata.reflection = Sdf_SystemProperties_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Sdf_ObjectProperties::kSystemTypeFieldNumber;
const int Sdf_ObjectProperties::kObjectTypeFieldNumber;
const int Sdf_ObjectProperties::kPropertiesFieldNumber;
#endif  // !_MSC_VER

Sdf_ObjectProperties::Sdf_ObjectProperties()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Sdf_ObjectProperties::InitAsDefaultInstance() {
}

Sdf_ObjectProperties::Sdf_ObjectProperties(const Sdf_ObjectProperties& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Sdf_ObjectProperties::SharedCtor() {
  _cached_size_ = 0;
  systemtype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  objecttype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Sdf_ObjectProperties::~Sdf_ObjectProperties() {
  SharedDtor();
}

void Sdf_ObjectProperties::SharedDtor() {
  if (systemtype_ != &::google::protobuf::internal::kEmptyString) {
    delete systemtype_;
  }
  if (objecttype_ != &::google::protobuf::internal::kEmptyString) {
    delete objecttype_;
  }
  if (this != default_instance_) {
  }
}

void Sdf_ObjectProperties::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Sdf_ObjectProperties::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Sdf_ObjectProperties_descriptor_;
}

const Sdf_ObjectProperties& Sdf_ObjectProperties::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdf_2eproto();  return *default_instance_;
}

Sdf_ObjectProperties* Sdf_ObjectProperties::default_instance_ = NULL;

Sdf_ObjectProperties* Sdf_ObjectProperties::New() const {
  return new Sdf_ObjectProperties;
}

void Sdf_ObjectProperties::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_systemtype()) {
      if (systemtype_ != &::google::protobuf::internal::kEmptyString) {
        systemtype_->clear();
      }
    }
    if (has_objecttype()) {
      if (objecttype_ != &::google::protobuf::internal::kEmptyString) {
        objecttype_->clear();
      }
    }
  }
  properties_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Sdf_ObjectProperties::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string systemType = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_systemtype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->systemtype().data(), this->systemtype().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(170)) goto parse_objectType;
        break;
      }
      
      // optional string objectType = 21;
      case 21: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_objectType:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_objecttype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->objecttype().data(), this->objecttype().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(178)) goto parse_properties;
        break;
      }
      
      // repeated .Proto.Property properties = 22;
      case 22: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_properties:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_properties()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(178)) goto parse_properties;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Sdf_ObjectProperties::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string systemType = 20;
  if (has_systemtype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->systemtype().data(), this->systemtype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      20, this->systemtype(), output);
  }
  
  // optional string objectType = 21;
  if (has_objecttype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->objecttype().data(), this->objecttype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      21, this->objecttype(), output);
  }
  
  // repeated .Proto.Property properties = 22;
  for (int i = 0; i < this->properties_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      22, this->properties(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Sdf_ObjectProperties::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string systemType = 20;
  if (has_systemtype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->systemtype().data(), this->systemtype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        20, this->systemtype(), target);
  }
  
  // optional string objectType = 21;
  if (has_objecttype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->objecttype().data(), this->objecttype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        21, this->objecttype(), target);
  }
  
  // repeated .Proto.Property properties = 22;
  for (int i = 0; i < this->properties_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        22, this->properties(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Sdf_ObjectProperties::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string systemType = 20;
    if (has_systemtype()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->systemtype());
    }
    
    // optional string objectType = 21;
    if (has_objecttype()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->objecttype());
    }
    
  }
  // repeated .Proto.Property properties = 22;
  total_size += 2 * this->properties_size();
  for (int i = 0; i < this->properties_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->properties(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Sdf_ObjectProperties::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Sdf_ObjectProperties* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Sdf_ObjectProperties*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Sdf_ObjectProperties::MergeFrom(const Sdf_ObjectProperties& from) {
  GOOGLE_CHECK_NE(&from, this);
  properties_.MergeFrom(from.properties_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_systemtype()) {
      set_systemtype(from.systemtype());
    }
    if (from.has_objecttype()) {
      set_objecttype(from.objecttype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Sdf_ObjectProperties::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sdf_ObjectProperties::CopyFrom(const Sdf_ObjectProperties& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sdf_ObjectProperties::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  for (int i = 0; i < properties_size(); i++) {
    if (!this->properties(i).IsInitialized()) return false;
  }
  return true;
}

void Sdf_ObjectProperties::Swap(Sdf_ObjectProperties* other) {
  if (other != this) {
    std::swap(systemtype_, other->systemtype_);
    std::swap(objecttype_, other->objecttype_);
    properties_.Swap(&other->properties_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Sdf_ObjectProperties::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Sdf_ObjectProperties_descriptor_;
  metadata.reflection = Sdf_ObjectProperties_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Sdf_Object::kNameFieldNumber;
const int Sdf_Object::kObjectPropertiesFieldNumber;
#endif  // !_MSC_VER

Sdf_Object::Sdf_Object()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Sdf_Object::InitAsDefaultInstance() {
}

Sdf_Object::Sdf_Object(const Sdf_Object& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Sdf_Object::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Sdf_Object::~Sdf_Object() {
  SharedDtor();
}

void Sdf_Object::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void Sdf_Object::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Sdf_Object::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Sdf_Object_descriptor_;
}

const Sdf_Object& Sdf_Object::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdf_2eproto();  return *default_instance_;
}

Sdf_Object* Sdf_Object::default_instance_ = NULL;

Sdf_Object* Sdf_Object::New() const {
  return new Sdf_Object;
}

void Sdf_Object::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  objectproperties_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Sdf_Object::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 30;
      case 30: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(250)) goto parse_objectProperties;
        break;
      }
      
      // repeated .Proto.Sdf.ObjectProperties objectProperties = 31;
      case 31: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_objectProperties:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_objectproperties()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(250)) goto parse_objectProperties;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Sdf_Object::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 30;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      30, this->name(), output);
  }
  
  // repeated .Proto.Sdf.ObjectProperties objectProperties = 31;
  for (int i = 0; i < this->objectproperties_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      31, this->objectproperties(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Sdf_Object::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 30;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        30, this->name(), target);
  }
  
  // repeated .Proto.Sdf.ObjectProperties objectProperties = 31;
  for (int i = 0; i < this->objectproperties_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        31, this->objectproperties(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Sdf_Object::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 30;
    if (has_name()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
  }
  // repeated .Proto.Sdf.ObjectProperties objectProperties = 31;
  total_size += 2 * this->objectproperties_size();
  for (int i = 0; i < this->objectproperties_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->objectproperties(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Sdf_Object::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Sdf_Object* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Sdf_Object*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Sdf_Object::MergeFrom(const Sdf_Object& from) {
  GOOGLE_CHECK_NE(&from, this);
  objectproperties_.MergeFrom(from.objectproperties_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Sdf_Object::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sdf_Object::CopyFrom(const Sdf_Object& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sdf_Object::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  for (int i = 0; i < objectproperties_size(); i++) {
    if (!this->objectproperties(i).IsInitialized()) return false;
  }
  return true;
}

void Sdf_Object::Swap(Sdf_Object* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    objectproperties_.Swap(&other->objectproperties_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Sdf_Object::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Sdf_Object_descriptor_;
  metadata.reflection = Sdf_Object_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Sdf_Link::kSubjectFieldNumber;
const int Sdf_Link::kObserverFieldNumber;
const int Sdf_Link::kSubjectSystemFieldNumber;
const int Sdf_Link::kObserverSystemFieldNumber;
#endif  // !_MSC_VER

Sdf_Link::Sdf_Link()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Sdf_Link::InitAsDefaultInstance() {
}

Sdf_Link::Sdf_Link(const Sdf_Link& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Sdf_Link::SharedCtor() {
  _cached_size_ = 0;
  subject_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  observer_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  subjectsystem_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  observersystem_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Sdf_Link::~Sdf_Link() {
  SharedDtor();
}

void Sdf_Link::SharedDtor() {
  if (subject_ != &::google::protobuf::internal::kEmptyString) {
    delete subject_;
  }
  if (observer_ != &::google::protobuf::internal::kEmptyString) {
    delete observer_;
  }
  if (subjectsystem_ != &::google::protobuf::internal::kEmptyString) {
    delete subjectsystem_;
  }
  if (observersystem_ != &::google::protobuf::internal::kEmptyString) {
    delete observersystem_;
  }
  if (this != default_instance_) {
  }
}

void Sdf_Link::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Sdf_Link::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Sdf_Link_descriptor_;
}

const Sdf_Link& Sdf_Link::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdf_2eproto();  return *default_instance_;
}

Sdf_Link* Sdf_Link::default_instance_ = NULL;

Sdf_Link* Sdf_Link::New() const {
  return new Sdf_Link;
}

void Sdf_Link::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_subject()) {
      if (subject_ != &::google::protobuf::internal::kEmptyString) {
        subject_->clear();
      }
    }
    if (has_observer()) {
      if (observer_ != &::google::protobuf::internal::kEmptyString) {
        observer_->clear();
      }
    }
    if (has_subjectsystem()) {
      if (subjectsystem_ != &::google::protobuf::internal::kEmptyString) {
        subjectsystem_->clear();
      }
    }
    if (has_observersystem()) {
      if (observersystem_ != &::google::protobuf::internal::kEmptyString) {
        observersystem_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Sdf_Link::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string subject = 40;
      case 40: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_subject()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->subject().data(), this->subject().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(330)) goto parse_observer;
        break;
      }
      
      // required string observer = 41;
      case 41: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_observer:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_observer()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->observer().data(), this->observer().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(338)) goto parse_subjectSystem;
        break;
      }
      
      // required string subjectSystem = 42;
      case 42: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_subjectSystem:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_subjectsystem()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->subjectsystem().data(), this->subjectsystem().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(346)) goto parse_observerSystem;
        break;
      }
      
      // required string observerSystem = 43;
      case 43: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_observerSystem:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_observersystem()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->observersystem().data(), this->observersystem().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Sdf_Link::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string subject = 40;
  if (has_subject()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->subject().data(), this->subject().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      40, this->subject(), output);
  }
  
  // required string observer = 41;
  if (has_observer()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->observer().data(), this->observer().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      41, this->observer(), output);
  }
  
  // required string subjectSystem = 42;
  if (has_subjectsystem()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->subjectsystem().data(), this->subjectsystem().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      42, this->subjectsystem(), output);
  }
  
  // required string observerSystem = 43;
  if (has_observersystem()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->observersystem().data(), this->observersystem().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      43, this->observersystem(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Sdf_Link::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string subject = 40;
  if (has_subject()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->subject().data(), this->subject().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        40, this->subject(), target);
  }
  
  // required string observer = 41;
  if (has_observer()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->observer().data(), this->observer().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        41, this->observer(), target);
  }
  
  // required string subjectSystem = 42;
  if (has_subjectsystem()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->subjectsystem().data(), this->subjectsystem().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        42, this->subjectsystem(), target);
  }
  
  // required string observerSystem = 43;
  if (has_observersystem()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->observersystem().data(), this->observersystem().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        43, this->observersystem(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Sdf_Link::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string subject = 40;
    if (has_subject()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->subject());
    }
    
    // required string observer = 41;
    if (has_observer()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->observer());
    }
    
    // required string subjectSystem = 42;
    if (has_subjectsystem()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->subjectsystem());
    }
    
    // required string observerSystem = 43;
    if (has_observersystem()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->observersystem());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Sdf_Link::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Sdf_Link* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Sdf_Link*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Sdf_Link::MergeFrom(const Sdf_Link& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_subject()) {
      set_subject(from.subject());
    }
    if (from.has_observer()) {
      set_observer(from.observer());
    }
    if (from.has_subjectsystem()) {
      set_subjectsystem(from.subjectsystem());
    }
    if (from.has_observersystem()) {
      set_observersystem(from.observersystem());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Sdf_Link::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sdf_Link::CopyFrom(const Sdf_Link& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sdf_Link::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  
  return true;
}

void Sdf_Link::Swap(Sdf_Link* other) {
  if (other != this) {
    std::swap(subject_, other->subject_);
    std::swap(observer_, other->observer_);
    std::swap(subjectsystem_, other->subjectsystem_);
    std::swap(observersystem_, other->observersystem_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Sdf_Link::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Sdf_Link_descriptor_;
  metadata.reflection = Sdf_Link_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Sdf::kNameFieldNumber;
const int Sdf::kSystemPropertiesFieldNumber;
const int Sdf::kObjectsFieldNumber;
const int Sdf::kLinksFieldNumber;
#endif  // !_MSC_VER

Sdf::Sdf()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Sdf::InitAsDefaultInstance() {
}

Sdf::Sdf(const Sdf& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Sdf::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Sdf::~Sdf() {
  SharedDtor();
}

void Sdf::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void Sdf::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Sdf::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Sdf_descriptor_;
}

const Sdf& Sdf::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdf_2eproto();  return *default_instance_;
}

Sdf* Sdf::default_instance_ = NULL;

Sdf* Sdf::New() const {
  return new Sdf;
}

void Sdf::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  systemproperties_.Clear();
  objects_.Clear();
  links_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Sdf::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_systemProperties;
        break;
      }
      
      // repeated .Proto.Sdf.SystemProperties systemProperties = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_systemProperties:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_systemproperties()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_systemProperties;
        if (input->ExpectTag(26)) goto parse_objects;
        break;
      }
      
      // repeated .Proto.Sdf.Object objects = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_objects:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_objects()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_objects;
        if (input->ExpectTag(34)) goto parse_links;
        break;
      }
      
      // repeated .Proto.Sdf.Link links = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_links:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_links()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_links;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Sdf::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // repeated .Proto.Sdf.SystemProperties systemProperties = 2;
  for (int i = 0; i < this->systemproperties_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->systemproperties(i), output);
  }
  
  // repeated .Proto.Sdf.Object objects = 3;
  for (int i = 0; i < this->objects_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->objects(i), output);
  }
  
  // repeated .Proto.Sdf.Link links = 4;
  for (int i = 0; i < this->links_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->links(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Sdf::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }
  
  // repeated .Proto.Sdf.SystemProperties systemProperties = 2;
  for (int i = 0; i < this->systemproperties_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->systemproperties(i), target);
  }
  
  // repeated .Proto.Sdf.Object objects = 3;
  for (int i = 0; i < this->objects_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->objects(i), target);
  }
  
  // repeated .Proto.Sdf.Link links = 4;
  for (int i = 0; i < this->links_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->links(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Sdf::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
  }
  // repeated .Proto.Sdf.SystemProperties systemProperties = 2;
  total_size += 1 * this->systemproperties_size();
  for (int i = 0; i < this->systemproperties_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->systemproperties(i));
  }
  
  // repeated .Proto.Sdf.Object objects = 3;
  total_size += 1 * this->objects_size();
  for (int i = 0; i < this->objects_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->objects(i));
  }
  
  // repeated .Proto.Sdf.Link links = 4;
  total_size += 1 * this->links_size();
  for (int i = 0; i < this->links_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->links(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Sdf::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Sdf* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Sdf*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Sdf::MergeFrom(const Sdf& from) {
  GOOGLE_CHECK_NE(&from, this);
  systemproperties_.MergeFrom(from.systemproperties_);
  objects_.MergeFrom(from.objects_);
  links_.MergeFrom(from.links_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Sdf::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sdf::CopyFrom(const Sdf& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sdf::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  for (int i = 0; i < systemproperties_size(); i++) {
    if (!this->systemproperties(i).IsInitialized()) return false;
  }
  for (int i = 0; i < objects_size(); i++) {
    if (!this->objects(i).IsInitialized()) return false;
  }
  for (int i = 0; i < links_size(); i++) {
    if (!this->links(i).IsInitialized()) return false;
  }
  return true;
}

void Sdf::Swap(Sdf* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    systemproperties_.Swap(&other->systemproperties_);
    objects_.Swap(&other->objects_);
    links_.Swap(&other->links_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Sdf::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Sdf_descriptor_;
  metadata.reflection = Sdf_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto

// @@protoc_insertion_point(global_scope)
