// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdf.proto

#ifndef PROTOBUF_sdf_2eproto__INCLUDED
#define PROTOBUF_sdf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "system.pb.h"
#include "property.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_sdf_2eproto();
void protobuf_AssignDesc_sdf_2eproto();
void protobuf_ShutdownFile_sdf_2eproto();

class Sdf;
class Sdf_Object;
class Sdf_ObjectProperties;
class Sdf_Link;

// ===================================================================

class Sdf_Object : public ::google::protobuf::Message {
 public:
  Sdf_Object();
  virtual ~Sdf_Object();
  
  Sdf_Object(const Sdf_Object& from);
  
  inline Sdf_Object& operator=(const Sdf_Object& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Sdf_Object& default_instance();
  
  void Swap(Sdf_Object* other);
  
  // implements Message ----------------------------------------------
  
  Sdf_Object* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sdf_Object& from);
  void MergeFrom(const Sdf_Object& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string name = 10;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 10;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // repeated .Sdf.ObjectProperties objectProperties = 11;
  inline int objectproperties_size() const;
  inline void clear_objectproperties();
  static const int kObjectPropertiesFieldNumber = 11;
  inline const ::Sdf_ObjectProperties& objectproperties(int index) const;
  inline ::Sdf_ObjectProperties* mutable_objectproperties(int index);
  inline ::Sdf_ObjectProperties* add_objectproperties();
  inline const ::google::protobuf::RepeatedPtrField< ::Sdf_ObjectProperties >&
      objectproperties() const;
  inline ::google::protobuf::RepeatedPtrField< ::Sdf_ObjectProperties >*
      mutable_objectproperties();
  
  // @@protoc_insertion_point(class_scope:Sdf.Object)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::Sdf_ObjectProperties > objectproperties_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_sdf_2eproto();
  friend void protobuf_AssignDesc_sdf_2eproto();
  friend void protobuf_ShutdownFile_sdf_2eproto();
  
  void InitAsDefaultInstance();
  static Sdf_Object* default_instance_;
};
// -------------------------------------------------------------------

class Sdf_ObjectProperties : public ::google::protobuf::Message {
 public:
  Sdf_ObjectProperties();
  virtual ~Sdf_ObjectProperties();
  
  Sdf_ObjectProperties(const Sdf_ObjectProperties& from);
  
  inline Sdf_ObjectProperties& operator=(const Sdf_ObjectProperties& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Sdf_ObjectProperties& default_instance();
  
  void Swap(Sdf_ObjectProperties* other);
  
  // implements Message ----------------------------------------------
  
  Sdf_ObjectProperties* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sdf_ObjectProperties& from);
  void MergeFrom(const Sdf_ObjectProperties& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string type = 20;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 20;
  inline const ::std::string& type() const;
  inline void set_type(const ::std::string& value);
  inline void set_type(const char* value);
  inline void set_type(const char* value, size_t size);
  inline ::std::string* mutable_type();
  inline ::std::string* release_type();
  
  // required .System.Type systemType = 21;
  inline bool has_systemtype() const;
  inline void clear_systemtype();
  static const int kSystemTypeFieldNumber = 21;
  inline ::System_Type systemtype() const;
  inline void set_systemtype(::System_Type value);
  
  // repeated .Property properties = 22;
  inline int properties_size() const;
  inline void clear_properties();
  static const int kPropertiesFieldNumber = 22;
  inline const ::Property& properties(int index) const;
  inline ::Property* mutable_properties(int index);
  inline ::Property* add_properties();
  inline const ::google::protobuf::RepeatedPtrField< ::Property >&
      properties() const;
  inline ::google::protobuf::RepeatedPtrField< ::Property >*
      mutable_properties();
  
  // @@protoc_insertion_point(class_scope:Sdf.ObjectProperties)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_systemtype();
  inline void clear_has_systemtype();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* type_;
  ::google::protobuf::RepeatedPtrField< ::Property > properties_;
  int systemtype_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_sdf_2eproto();
  friend void protobuf_AssignDesc_sdf_2eproto();
  friend void protobuf_ShutdownFile_sdf_2eproto();
  
  void InitAsDefaultInstance();
  static Sdf_ObjectProperties* default_instance_;
};
// -------------------------------------------------------------------

class Sdf_Link : public ::google::protobuf::Message {
 public:
  Sdf_Link();
  virtual ~Sdf_Link();
  
  Sdf_Link(const Sdf_Link& from);
  
  inline Sdf_Link& operator=(const Sdf_Link& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Sdf_Link& default_instance();
  
  void Swap(Sdf_Link* other);
  
  // implements Message ----------------------------------------------
  
  Sdf_Link* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sdf_Link& from);
  void MergeFrom(const Sdf_Link& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string subject = 30;
  inline bool has_subject() const;
  inline void clear_subject();
  static const int kSubjectFieldNumber = 30;
  inline const ::std::string& subject() const;
  inline void set_subject(const ::std::string& value);
  inline void set_subject(const char* value);
  inline void set_subject(const char* value, size_t size);
  inline ::std::string* mutable_subject();
  inline ::std::string* release_subject();
  
  // required string observer = 31;
  inline bool has_observer() const;
  inline void clear_observer();
  static const int kObserverFieldNumber = 31;
  inline const ::std::string& observer() const;
  inline void set_observer(const ::std::string& value);
  inline void set_observer(const char* value);
  inline void set_observer(const char* value, size_t size);
  inline ::std::string* mutable_observer();
  inline ::std::string* release_observer();
  
  // required .System.Type subjectSystemType = 32;
  inline bool has_subjectsystemtype() const;
  inline void clear_subjectsystemtype();
  static const int kSubjectSystemTypeFieldNumber = 32;
  inline ::System_Type subjectsystemtype() const;
  inline void set_subjectsystemtype(::System_Type value);
  
  // required .System.Type observerSystemType = 33;
  inline bool has_observersystemtype() const;
  inline void clear_observersystemtype();
  static const int kObserverSystemTypeFieldNumber = 33;
  inline ::System_Type observersystemtype() const;
  inline void set_observersystemtype(::System_Type value);
  
  // @@protoc_insertion_point(class_scope:Sdf.Link)
 private:
  inline void set_has_subject();
  inline void clear_has_subject();
  inline void set_has_observer();
  inline void clear_has_observer();
  inline void set_has_subjectsystemtype();
  inline void clear_has_subjectsystemtype();
  inline void set_has_observersystemtype();
  inline void clear_has_observersystemtype();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* subject_;
  ::std::string* observer_;
  int subjectsystemtype_;
  int observersystemtype_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_sdf_2eproto();
  friend void protobuf_AssignDesc_sdf_2eproto();
  friend void protobuf_ShutdownFile_sdf_2eproto();
  
  void InitAsDefaultInstance();
  static Sdf_Link* default_instance_;
};
// -------------------------------------------------------------------

class Sdf : public ::google::protobuf::Message {
 public:
  Sdf();
  virtual ~Sdf();
  
  Sdf(const Sdf& from);
  
  inline Sdf& operator=(const Sdf& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Sdf& default_instance();
  
  void Swap(Sdf* other);
  
  // implements Message ----------------------------------------------
  
  Sdf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sdf& from);
  void MergeFrom(const Sdf& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Sdf_Object Object;
  typedef Sdf_ObjectProperties ObjectProperties;
  typedef Sdf_Link Link;
  
  // accessors -------------------------------------------------------
  
  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // repeated .System systems = 2;
  inline int systems_size() const;
  inline void clear_systems();
  static const int kSystemsFieldNumber = 2;
  inline const ::System& systems(int index) const;
  inline ::System* mutable_systems(int index);
  inline ::System* add_systems();
  inline const ::google::protobuf::RepeatedPtrField< ::System >&
      systems() const;
  inline ::google::protobuf::RepeatedPtrField< ::System >*
      mutable_systems();
  
  // repeated .Sdf.Object objects = 3;
  inline int objects_size() const;
  inline void clear_objects();
  static const int kObjectsFieldNumber = 3;
  inline const ::Sdf_Object& objects(int index) const;
  inline ::Sdf_Object* mutable_objects(int index);
  inline ::Sdf_Object* add_objects();
  inline const ::google::protobuf::RepeatedPtrField< ::Sdf_Object >&
      objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::Sdf_Object >*
      mutable_objects();
  
  // repeated .Sdf.Link links = 4;
  inline int links_size() const;
  inline void clear_links();
  static const int kLinksFieldNumber = 4;
  inline const ::Sdf_Link& links(int index) const;
  inline ::Sdf_Link* mutable_links(int index);
  inline ::Sdf_Link* add_links();
  inline const ::google::protobuf::RepeatedPtrField< ::Sdf_Link >&
      links() const;
  inline ::google::protobuf::RepeatedPtrField< ::Sdf_Link >*
      mutable_links();
  
  // @@protoc_insertion_point(class_scope:Sdf)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::System > systems_;
  ::google::protobuf::RepeatedPtrField< ::Sdf_Object > objects_;
  ::google::protobuf::RepeatedPtrField< ::Sdf_Link > links_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_sdf_2eproto();
  friend void protobuf_AssignDesc_sdf_2eproto();
  friend void protobuf_ShutdownFile_sdf_2eproto();
  
  void InitAsDefaultInstance();
  static Sdf* default_instance_;
};
// ===================================================================


// ===================================================================

// Sdf_Object

// required string name = 10;
inline bool Sdf_Object::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sdf_Object::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Sdf_Object::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Sdf_Object::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Sdf_Object::name() const {
  return *name_;
}
inline void Sdf_Object::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Sdf_Object::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Sdf_Object::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Sdf_Object::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Sdf_Object::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .Sdf.ObjectProperties objectProperties = 11;
inline int Sdf_Object::objectproperties_size() const {
  return objectproperties_.size();
}
inline void Sdf_Object::clear_objectproperties() {
  objectproperties_.Clear();
}
inline const ::Sdf_ObjectProperties& Sdf_Object::objectproperties(int index) const {
  return objectproperties_.Get(index);
}
inline ::Sdf_ObjectProperties* Sdf_Object::mutable_objectproperties(int index) {
  return objectproperties_.Mutable(index);
}
inline ::Sdf_ObjectProperties* Sdf_Object::add_objectproperties() {
  return objectproperties_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Sdf_ObjectProperties >&
Sdf_Object::objectproperties() const {
  return objectproperties_;
}
inline ::google::protobuf::RepeatedPtrField< ::Sdf_ObjectProperties >*
Sdf_Object::mutable_objectproperties() {
  return &objectproperties_;
}

// -------------------------------------------------------------------

// Sdf_ObjectProperties

// optional string type = 20;
inline bool Sdf_ObjectProperties::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sdf_ObjectProperties::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Sdf_ObjectProperties::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Sdf_ObjectProperties::clear_type() {
  if (type_ != &::google::protobuf::internal::kEmptyString) {
    type_->clear();
  }
  clear_has_type();
}
inline const ::std::string& Sdf_ObjectProperties::type() const {
  return *type_;
}
inline void Sdf_ObjectProperties::set_type(const ::std::string& value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    type_ = new ::std::string;
  }
  type_->assign(value);
}
inline void Sdf_ObjectProperties::set_type(const char* value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    type_ = new ::std::string;
  }
  type_->assign(value);
}
inline void Sdf_ObjectProperties::set_type(const char* value, size_t size) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    type_ = new ::std::string;
  }
  type_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Sdf_ObjectProperties::mutable_type() {
  set_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    type_ = new ::std::string;
  }
  return type_;
}
inline ::std::string* Sdf_ObjectProperties::release_type() {
  clear_has_type();
  if (type_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = type_;
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required .System.Type systemType = 21;
inline bool Sdf_ObjectProperties::has_systemtype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Sdf_ObjectProperties::set_has_systemtype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Sdf_ObjectProperties::clear_has_systemtype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Sdf_ObjectProperties::clear_systemtype() {
  systemtype_ = 0;
  clear_has_systemtype();
}
inline ::System_Type Sdf_ObjectProperties::systemtype() const {
  return static_cast< ::System_Type >(systemtype_);
}
inline void Sdf_ObjectProperties::set_systemtype(::System_Type value) {
  GOOGLE_DCHECK(::System_Type_IsValid(value));
  set_has_systemtype();
  systemtype_ = value;
}

// repeated .Property properties = 22;
inline int Sdf_ObjectProperties::properties_size() const {
  return properties_.size();
}
inline void Sdf_ObjectProperties::clear_properties() {
  properties_.Clear();
}
inline const ::Property& Sdf_ObjectProperties::properties(int index) const {
  return properties_.Get(index);
}
inline ::Property* Sdf_ObjectProperties::mutable_properties(int index) {
  return properties_.Mutable(index);
}
inline ::Property* Sdf_ObjectProperties::add_properties() {
  return properties_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Property >&
Sdf_ObjectProperties::properties() const {
  return properties_;
}
inline ::google::protobuf::RepeatedPtrField< ::Property >*
Sdf_ObjectProperties::mutable_properties() {
  return &properties_;
}

// -------------------------------------------------------------------

// Sdf_Link

// required string subject = 30;
inline bool Sdf_Link::has_subject() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sdf_Link::set_has_subject() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Sdf_Link::clear_has_subject() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Sdf_Link::clear_subject() {
  if (subject_ != &::google::protobuf::internal::kEmptyString) {
    subject_->clear();
  }
  clear_has_subject();
}
inline const ::std::string& Sdf_Link::subject() const {
  return *subject_;
}
inline void Sdf_Link::set_subject(const ::std::string& value) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    subject_ = new ::std::string;
  }
  subject_->assign(value);
}
inline void Sdf_Link::set_subject(const char* value) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    subject_ = new ::std::string;
  }
  subject_->assign(value);
}
inline void Sdf_Link::set_subject(const char* value, size_t size) {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    subject_ = new ::std::string;
  }
  subject_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Sdf_Link::mutable_subject() {
  set_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    subject_ = new ::std::string;
  }
  return subject_;
}
inline ::std::string* Sdf_Link::release_subject() {
  clear_has_subject();
  if (subject_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = subject_;
    subject_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string observer = 31;
inline bool Sdf_Link::has_observer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Sdf_Link::set_has_observer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Sdf_Link::clear_has_observer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Sdf_Link::clear_observer() {
  if (observer_ != &::google::protobuf::internal::kEmptyString) {
    observer_->clear();
  }
  clear_has_observer();
}
inline const ::std::string& Sdf_Link::observer() const {
  return *observer_;
}
inline void Sdf_Link::set_observer(const ::std::string& value) {
  set_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    observer_ = new ::std::string;
  }
  observer_->assign(value);
}
inline void Sdf_Link::set_observer(const char* value) {
  set_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    observer_ = new ::std::string;
  }
  observer_->assign(value);
}
inline void Sdf_Link::set_observer(const char* value, size_t size) {
  set_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    observer_ = new ::std::string;
  }
  observer_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Sdf_Link::mutable_observer() {
  set_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    observer_ = new ::std::string;
  }
  return observer_;
}
inline ::std::string* Sdf_Link::release_observer() {
  clear_has_observer();
  if (observer_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = observer_;
    observer_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required .System.Type subjectSystemType = 32;
inline bool Sdf_Link::has_subjectsystemtype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Sdf_Link::set_has_subjectsystemtype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Sdf_Link::clear_has_subjectsystemtype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Sdf_Link::clear_subjectsystemtype() {
  subjectsystemtype_ = 0;
  clear_has_subjectsystemtype();
}
inline ::System_Type Sdf_Link::subjectsystemtype() const {
  return static_cast< ::System_Type >(subjectsystemtype_);
}
inline void Sdf_Link::set_subjectsystemtype(::System_Type value) {
  GOOGLE_DCHECK(::System_Type_IsValid(value));
  set_has_subjectsystemtype();
  subjectsystemtype_ = value;
}

// required .System.Type observerSystemType = 33;
inline bool Sdf_Link::has_observersystemtype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Sdf_Link::set_has_observersystemtype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Sdf_Link::clear_has_observersystemtype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Sdf_Link::clear_observersystemtype() {
  observersystemtype_ = 0;
  clear_has_observersystemtype();
}
inline ::System_Type Sdf_Link::observersystemtype() const {
  return static_cast< ::System_Type >(observersystemtype_);
}
inline void Sdf_Link::set_observersystemtype(::System_Type value) {
  GOOGLE_DCHECK(::System_Type_IsValid(value));
  set_has_observersystemtype();
  observersystemtype_ = value;
}

// -------------------------------------------------------------------

// Sdf

// required string name = 1;
inline bool Sdf::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sdf::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Sdf::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Sdf::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Sdf::name() const {
  return *name_;
}
inline void Sdf::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Sdf::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Sdf::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Sdf::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Sdf::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .System systems = 2;
inline int Sdf::systems_size() const {
  return systems_.size();
}
inline void Sdf::clear_systems() {
  systems_.Clear();
}
inline const ::System& Sdf::systems(int index) const {
  return systems_.Get(index);
}
inline ::System* Sdf::mutable_systems(int index) {
  return systems_.Mutable(index);
}
inline ::System* Sdf::add_systems() {
  return systems_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::System >&
Sdf::systems() const {
  return systems_;
}
inline ::google::protobuf::RepeatedPtrField< ::System >*
Sdf::mutable_systems() {
  return &systems_;
}

// repeated .Sdf.Object objects = 3;
inline int Sdf::objects_size() const {
  return objects_.size();
}
inline void Sdf::clear_objects() {
  objects_.Clear();
}
inline const ::Sdf_Object& Sdf::objects(int index) const {
  return objects_.Get(index);
}
inline ::Sdf_Object* Sdf::mutable_objects(int index) {
  return objects_.Mutable(index);
}
inline ::Sdf_Object* Sdf::add_objects() {
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Sdf_Object >&
Sdf::objects() const {
  return objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::Sdf_Object >*
Sdf::mutable_objects() {
  return &objects_;
}

// repeated .Sdf.Link links = 4;
inline int Sdf::links_size() const {
  return links_.size();
}
inline void Sdf::clear_links() {
  links_.Clear();
}
inline const ::Sdf_Link& Sdf::links(int index) const {
  return links_.Get(index);
}
inline ::Sdf_Link* Sdf::mutable_links(int index) {
  return links_.Mutable(index);
}
inline ::Sdf_Link* Sdf::add_links() {
  return links_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Sdf_Link >&
Sdf::links() const {
  return links_;
}
inline ::google::protobuf::RepeatedPtrField< ::Sdf_Link >*
Sdf::mutable_links() {
  return &links_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sdf_2eproto__INCLUDED
